org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
PREZZENCE_SUPABASE_URL=https://djwtmlvorvuhgaksqirc.supabase.co
PREZZENCE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqd3RtbHZvcnZ1aGdha3NxaXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4MjE2MTgsImV4cCI6MjA5NDM5NzYxOH0.c5EuBaf5UBjPlKscPl9kmOu4D02679oxHb5OMoC2bTA

